#!/usr/bin/env bash
# Shared PPDM environment config file helpers.
#
# ppdm-env-check.sh writes PPDM_ENV_FILE after authentication.
# Other scripts call load_ppdm_env to read it (no shell source required).
#
# Override path: export PPDM_ENV_FILE=/path/to/ppdm-env.cfg

PPDM_ENV_CFG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PPDM_ENV_FILE="${PPDM_ENV_FILE:-${PPDM_ENV_CFG_DIR}/.ppdm-env.cfg}"

_ppdm_env_cfg_die() {
  if declare -F die >/dev/null 2>&1; then
    die "$@"
  fi
  printf '[ERROR] %s\r\n' "$*" >&2
  exit 1
}

_ppdm_env_cfg_log_info() {
  if declare -F log_info >/dev/null 2>&1; then
    log_info "$@"
  else
    printf '[INFO] %s\r\n' "$*" >&2
  fi
}

wipe_ppdm_env_file() {
  if [[ -f "$PPDM_ENV_FILE" ]]; then
    _ppdm_env_cfg_log_info "Removing existing PPDM env file: ${PPDM_ENV_FILE}"
    rm -f "$PPDM_ENV_FILE"
  fi
}

write_ppdm_env_file() {
  local tmp

  [[ -n "${PPDM_BASE_URL:-}" ]] || _ppdm_env_cfg_die "Cannot write PPDM env file: PPDM_BASE_URL is empty"
  [[ -n "${PPDM_TOKEN:-}" ]] || _ppdm_env_cfg_die "Cannot write PPDM env file: PPDM_TOKEN is empty"

  tmp="$(mktemp "${PPDM_ENV_FILE}.XXXXXX")"
  {
    printf '# PPDM environment — generated by ppdm-env-check.sh\n'
    printf '# Do not commit; chmod 600 recommended\n'
    printf 'PPDM_BASE_URL=%q\n' "$PPDM_BASE_URL"
    printf 'PPDM_TOKEN=%q\n' "$PPDM_TOKEN"
    if [[ -n "${PPDM_CA_CERT:-}" ]]; then
      printf 'PPDM_CA_CERT=%q\n' "$PPDM_CA_CERT"
    fi
    if [[ -n "${PPDM_CURL_INSECURE:-}" ]]; then
      case "$(printf '%s' "$PPDM_CURL_INSECURE" | tr '[:upper:]' '[:lower:]')" in
        1|true|yes) printf 'PPDM_CURL_INSECURE=%q\n' "true" ;;
      esac
    fi
  } >"$tmp"
  chmod 600 "$tmp"
  mv -f "$tmp" "$PPDM_ENV_FILE"
  _ppdm_env_cfg_log_info "Wrote PPDM env file: ${PPDM_ENV_FILE}"
}

load_ppdm_env() {
  [[ -f "$PPDM_ENV_FILE" ]] || \
    _ppdm_env_cfg_die "PPDM env file not found: ${PPDM_ENV_FILE} — run ./ppdm-env-check.sh first"

  # shellcheck source=/dev/null
  set -a
  # shellcheck disable=SC1090
  source "$PPDM_ENV_FILE"
  set +a

  [[ -n "${PPDM_BASE_URL:-}" ]] || \
    _ppdm_env_cfg_die "PPDM env file is missing PPDM_BASE_URL: ${PPDM_ENV_FILE}"
  [[ -n "${PPDM_TOKEN:-}" ]] || \
    _ppdm_env_cfg_die "PPDM env file is missing PPDM_TOKEN: ${PPDM_ENV_FILE}"

  _ppdm_env_cfg_log_info "Loaded PPDM credentials from ${PPDM_ENV_FILE}"
}

ensure_ppdm_env() {
  if [[ -n "${PPDM_BASE_URL:-}" && -n "${PPDM_TOKEN:-}" ]]; then
    _ppdm_env_cfg_log_info "Using PPDM credentials from environment"
    return 0
  fi
  load_ppdm_env
}
